BASE=copy_router
PARTS=
A_PLATES=a1_link_holes a3_link_outlines
B_PLATES=b1_bot_holes b2_bot_pocket b3_bot_outlines

EXTRA_LIB=../../_lib/edge_tabs.scad ../../_lib/fillets.scad ../../_lib/supported_rail.scad
CAMERA=-15,300,68,66,0,37,1900

include ../../_lib/makefile.inc
