BASE=domo
EXTRA_LIB=../../_lib/edge_tabs.scad ../../_lib/fillets.scad ../../_lib/bezier.scad ../../_lib/trig.scad

A_PLATES=a1_sides_pocket a2_sides_fake_pocket1 a2_sides_fake_pocket2 a4_sides_outline

include ../../_lib/makefile.inc
