BASE=center_finder
PARTS=
A_PLATES=a1_holes a2_outline
B_PLATES=b1_pocket b2_outline
EXTRA_LIB=../../_lib/bezier.scad ../../_lib/fillets.scad ../../_lib/trig.scad

CAMERA=71,51,77,44,0,342,600

include ../../_lib/makefile.inc
