BASE=tracks
A_PLATES=a1_sprocket_outline
B_PLATES=b1_mount_holes b2_mount_outline
C_PLATES=c1_foot_pocket c2_foot_outline
D_PLATES=d1_hole_jig d2_hole_jig2 d3_hole_jig3

EXTRA_LIB=../../_lib/edge_tabs.scad ../../_lib/fillets.scad

CAMERA=-113,148,181,56,0,298,1400

include ../../_lib/makefile.inc
