BASE=dust_pipe_tail
# TODO make the main makefile support a<n> and b<n> prefixes so 4 can be
# treated as a plate with its own combined.
PARTS=4_verticals
PLATES=1_hole 2_pocket 3_outline
CAMERA=496,48,97,67,0,44,1425

include ../../_lib/makefile.inc
