BASE=dust_pipe_tail
A_PLATES=a1_hole a2_pocket a3_outline
B_PLATES=b1_verticals
C_PLATES=c1_mount_hole c2_mount_pocket c3_mount_outline
LIBS=../../_lib/fillets.scad
CAMERA=496,48,97,67,0,44,1425

include ../../_lib/makefile.inc
