BASE=dust_pipe_tail
A_PLATES=a1_hole a2_pocket a3_outline
B_PLATES=b1_verticals
C_PLATES=c1_mount_hole c2_mount_pocket c3_mount_outline
LIBS=../../_lib/fillets.scad shield.scad
CAMERA=305,116,75,72,0,30,2300

include ../../_lib/makefile.inc
