BASE=cabinet_tray
A_PLATES=a1_pocket a2_outline
B_PLATES=b1_fake_pocket1 b1_fake_pocket2 b3_outline

EXTRA_LIB=../../_lib/edge_tabs.scad ../../_lib/fillets.scad

CAMERA=20,100,90,65,0,25,900

include ../../_lib/makefile.inc
