BASE=book_stand
A_PLATES=a1_column_pocket a2_column_outline
B_PLATES=b1_fake_pocket1 b2_fake_pocket2 b3_outline
C_PLATES=c1_holes c2_outline
D_PLATES=d1_holes d2_outline
E_PLATES=e1_pocket e2_outline
F_PLATES=f0_holes f1_fake_pocket1 f2_fake_pocket2 f3_outline
G_PLATES=g1_pocket g2_outline

EXTRA_LIB=../../_lib/bezier.scad ../../_lib/edge_tabs.scad ../../_lib/trig.scad ../../_lib/fillets.scad ../../_lib/repeat.scad

CAMERA=250,140,502,62,0,216,3600

include ../../_lib/makefile.inc
