BASE=toy_chest
PLATES=1_corner_rounding  2_pocket  3_bottom_pocket  4_outline
B_PLATES=b1_corner_rounding b2_outline
EXTRA_LIB=../../_lib/edge_tabs.scad ../../_lib/fillets.scad

include ../../_lib/makefile.inc

