BASE=toy_chest
PLATES=2_pocket 4_outline
A_PLATES=a1_fake_bottom_pocket a2_fake_bottom_pocket a3_outline
#PLATES=2_pocket 3a_fake_bottom_pocket 3b_fake_bottom_pocket 4_outline
B_PLATES=b1_corner_rounding b2_outline
C_PLATES=c1_pocket c1b_pocket c2_outline
D_PLATES=d1_slats_pocket d2_slats_outline
E_PLATES=e1_pocket1 e2_rabbet1a e3_rabbet1b e4_outline1 e4_outline1b e4_outline1c \
	e5_pocket2 e6_rabbet2a e7_rabbet2b e8_outline2 e8_outline2b e8_outline2c \
	e9_pocket3 e10_rabbet3a e11_rabbet3b e12_outline3 e12_outline3b e12_outline3c \
	e13_pocket4 e14_rabbet4a e15_rabbet4b e16_outline4 e16_outline4b e16_outline4c
F_PLATES=f1_pocket0 f1_pocket1 f1_pocket2 f1_pocket3 f1_pocket4 f2_outline

EXTRA_LIB=../../_lib/edge_tabs.scad ../../_lib/fillets.scad production_lib.scad

# Regular demo
CAMERA=90,-102,100,73,0,315,800
# Flat demo
#CAMERA=500,500,0,0,0,0,3100

include ../../_lib/makefile.inc

