BASE=pipe_hanger
PARTS=
# omit 3_cut_tabs until it works better
PLATES=1_pocket 2_obliterate_middle 3_outline
EXTRA_LIB=../../_lib/trig.scad ../../_lib/repeat.scad
CAMERA=101,0,100,90,0,0,611
PROJECTION=o

include ../../_lib/makefile.inc
