BASE=tape_rack
A_PLATES=a1_cross_outline
B_PLATES=b1_pockets b2_pockets b3_outlines
EXTRA_LIB=../../_lib/edge_tabs.scad ../../_lib/fillets.scad

CAMERA=108,28,-29,59,0,315,900

include ../../_lib/makefile.inc
